<?php

name: RPKitCMD
author: David2020xD
api: 3.0.0-ALPHA9
version: 1.0
main: David202020/RPKitCMD

command:
	wizard:
		description: get a wand
		usage: /wizard
	knight:
		description: recieve your armor/weapons
		usage: /knight

permissions:
	wizard:
		default: true
	knight:
		default: true
